Giza Bot Updates (#601)
* Update gitignore.

* Revert "Update gitignore."

This reverts commit e10f99b0583d510c46ed758945b1e757aa956b72.

* Council Daily Bot

* Update .gitignore

* Update termBlocksRemaining calculation.

* update config, hidden threads

* prettier

* read proposal updates from block events, simplify tests

* no proposal details in announce:heartbeat

* tgbot:activeProposals: ignore failing proposals

* use joystream-lib + proposal reminders

* joystreambot: Giza upgrade

* print options, fix types

* report-generator: Update paths + links

 - Fix outdated spending proposals file path
 - Fix wrong last budget proposal link
 - Update repo path

* report-generator: Giza cleanup

* tokenomics-generator: refactor Working Groups + template

* report generator: bump @joystream/types to 0.17.3, update lib, fixes

* error handling

* merge `scripts/storagesizebot`

* merge `scripts/joystreamvideobot`

* prettier

* bot: factor out video util.ts

* merge `scripts/wg-bot, move `joystream/api_extension.ts` to lib

bot: rename, wg/discord.ts > wg.index.ts

* wg: processGroupEvents, refactor discord channel mapping

* fix missingPropsalVotes

* bump discord to 13.6.0 (requires node 16)

* bot: personalized `/proposals` response

* Test events for wg-bot simulate

* Two bugfixes for Opening events

* report-generator: Fix bug on formatChange

* bot: factor out db + discord, detailed Storage stats

* bot: reduce logging, `yarn trace` for extras

* video bot: fix/refactor

TODO
```
(node:556327) DeprecationWarning: The message event is deprecated. Use messageCreate instead
(node:556327) DeprecationWarning: Passing strings for MessageEmbed#setAuthor is deprecated. Pass a sole object instead.
DiscordAPIError: Cannot send an empty message
```

* tokenomics: fix missing election stakes

* tokenomics: fix getApprovedBounties

* 1. Fixed MongoDB Warning:
"current Server Discovery and Monitoring engine is deprecated,
and will be removed in a future version.
 To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true }
to the MongoClient constructor".
2. Fixed Discord bob bug:
"Property 'getChatId' is missing in type".

* Step by step:
1) add next variables in .env:
DISCORD_TOKEN_EN,
DISCORD_TOKEN_RU.
2) Improve "help" command for the English bot.
Now messages are deleted after timeout in Tg and Discord
(was only in Discord).
3) add command "start" equals to "scoring".
4) Translated bot into Russian language
(Change text, operate variable 'dayText' and other little things).

* Update Readme

* tokenomics: count only active workers (keep listing all)

* joystream-api: prettier

* api-examples: Giza types

* joystream-api: general, toHext, proposals, working-groups+

* joystream-api: fix errors related with giza release

* Fixed video bot errors

* tokenomics: more detailed timestamps + duration

* tokenomics: use UTC

* tokenomics: rename Gamma to HR WG

* council minutes template headline (Sumer -> Giza)

* wg bot `getStakeUpdatedEmbed`: cope with empty stake

Co-authored-by: Oleksandr Korniienko <oleksanderkorn@gmail.com>
Co-authored-by: Joystream Stats <dev@joystreamstats.live>
Co-authored-by: Ricardo Maltez <ricardomaltez@gmail.com>
Co-authored-by: singulart <serpian@gmail.com>
Co-authored-by: Ars44 <Hrieleght2>