video bot: fix/refactor
TODO
```
(node:556327) DeprecationWarning: The message event is deprecated. Use messageCreate instead
(node:556327) DeprecationWarning: Passing strings for MessageEmbed#setAuthor is deprecated. Pass a sole object instead.
DiscordAPIError: Cannot send an empty message
```